---
version: 2

project_name: pi-stalker-radio-service

builds:
  - id: binary-build # ID of the build
    main: ./cmd/main.go # Path to main.go file or main package
    binary: app # Binary name
    # Custom ldflags
    ldflags:
      - -s -w -X main.version={{.Version}}
    # Custom environment variables to be set during the builds
    env:
      - CGO_ENABLED=0
    # GOOS list to build for
    goos:
      - linux
#      - darwin
#      - windows
    # GOARCH to build for
    goarch:
#      - amd64
#      - arm64
      - arm
