---
version: 2

project_name: pi-storyteller

builds:
  - id: binary-build # ID of the build
    main: ./cmd/main.go # Path to main.go file or main package
    binary: bin # Binary name
    # Custom ldflags
    ldflags:
      - -s -w -X main.version={{.Version}}
    # Custom environment variables to be set during the builds
    env:
      - CGO_ENABLED=0
    # GOOS list to build for
    goos:
      - linux
    # GOARCH to build for
    goarch:
      - arm
