# ./internal/configs/app.go
app:
  name: "app"
  mode: "production" # develop | production | debug
  http_port: "8080"
  rpc_port: "8088"
  priority_list: [] # Example, ["USERNAME"]
# ./internal/configs/logger.go
logger:
  level: "warn" # warn | error | debug | info
  format: "json" # json | pretty
# ./internal/configs/metrics.go
metrics:
  enabled: "false"
# ./internal/configs/kandinsky.go
kandinsky:
  debug: "false"
  base_url: "https://api-key.fusionbrain.ai"
  key: ""
  secret: ""
# ./internal/configs/chatgpt.go
chatgpt:
  debug: "false"
  base_url: "https://api.openai.com"
  secret: ""
# ./internal/configs/telegram.go
telegram:
  lang: "" # ru | en
  chat_id: "0"
  name: ""
  token: ""
