app:
  name: "app"
  mode: "debug"
  http_port: "8080"
  rpc_port: "8088"
  assets_path: "assets"
  priority_list: []
logger:
  level: "debug"
  format: "json"
kandinsky:
  debug: true
  base_url: "https://api-key.fusionbrain.ai"
  key: ""
  secret: ""
telegram:
  name: ""
  token: ""
