---
version: '3'

tasks:
  # Run using docker
  docker:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmd: docker-compose up -d app

  # Run locally with hot-reload
  local:
    cmd: air -d

  # Update DI deps
  wire:
    cmd: cd internal && wire

  build:
    goreleaser --skip=publish --snapshot --clean

  test:
    CGO_ENABLED=0 go test -cover -coverprofile=coverage.txt -covermode=atomic ./...