version: '3.9'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
      target: build
    volumes:
      - ./onnx:/onnx

  onnxserver:
    build: 
      context: .
      dockerfile: Dockerfile
      target: app
    volumes:
      - ./out:/app/out
      - ./weights:/app/weights
      - ./scripts:/app/scripts
      - ./templates:/app/templates
      - ./bin:/app/bin
    stdin_open: true
    tty: true
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.25'
    #       memory: 256M