// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/WildEgor/pi-storyteller/internal/adapters/bot"
	"github.com/WildEgor/pi-storyteller/internal/adapters/imaginator"
	"github.com/WildEgor/pi-storyteller/internal/adapters/monitor"
	"github.com/WildEgor/pi-storyteller/internal/adapters/textor"
	"github.com/WildEgor/pi-storyteller/internal/configs"
	"github.com/WildEgor/pi-storyteller/internal/handlers/http/http_error_handler"
	"github.com/WildEgor/pi-storyteller/internal/handlers/http/http_health_check_handler"
	"github.com/WildEgor/pi-storyteller/internal/handlers/http/metrics"
	"github.com/WildEgor/pi-storyteller/internal/handlers/tg/generate"
	"github.com/WildEgor/pi-storyteller/internal/handlers/tg/random"
	"github.com/WildEgor/pi-storyteller/internal/handlers/tg/start"
	"github.com/WildEgor/pi-storyteller/internal/routers"
	"github.com/WildEgor/pi-storyteller/internal/services/cronus"
	"github.com/WildEgor/pi-storyteller/internal/services/dispatcher"
	"github.com/WildEgor/pi-storyteller/internal/services/prompter"
	"github.com/WildEgor/pi-storyteller/internal/services/templater"
	"github.com/google/wire"
)

// Injectors from server.go:

// NewServer
func NewServer() (*App, error) {
	configurator := configs.NewConfigurator()
	appConfig := configs.NewAppConfig()
	loggerConfig := configs.NewLoggerConfig()
	errorsHandler := http_error_handler.NewErrorsHandler()
	healthCheckHandler := http_health_check_handler.NewHealthCheckHandler()
	healthRouter := routers.NewHealthRouter(healthCheckHandler)
	metricsHandler := http_metrics_handler.NewMetricsHandler()
	metricsConfig := configs.NewMetricsConfig()
	metricsRouter := routers.NewMetricsRouter(metricsHandler, metricsConfig)
	telegramBotConfig := configs.NewTelegramBotConfig()
	telegramBotAdapter := bot.NewTelegramBot(telegramBotConfig)
	promMetrics := monitor.NewPromMetrics(appConfig, metricsConfig)
	service := dispatcher.New(promMetrics)
	kandinskyConfig := configs.NewKandinskyConfig()
	kandinskyClientProvider := imaginator.NewKandinskyClientProvider(kandinskyConfig, appConfig)
	kandinskyAdapter := imaginator.NewKandinskyAdapter(kandinskyClientProvider)
	templaterService := templater.New()
	chatGPTConfig := configs.NewChatGPTConfig()
	chatGPTClientProvider := textor.NewChatGPTClientProvider(chatGPTConfig, appConfig)
	chatGPTAdapter := textor.NewChatGPTAdapter(chatGPTClientProvider)
	prompterService := prompter.New(chatGPTAdapter)
	generateHandler := tg_generate_handler.NewGenerateHandler(appConfig, service, kandinskyAdapter, templaterService, prompterService, telegramBotAdapter)
	startHandler := tg_start_handler.NewStartHandler(telegramBotAdapter)
	randomHandler := tg_random_handler.NewRandomHandler(appConfig, service, kandinskyAdapter, templaterService, prompterService, telegramBotAdapter)
	telegramRouter := routers.NewImageRouter(telegramBotAdapter, generateHandler, startHandler, randomHandler)
	cronusService := cronus.New(service, prompterService, telegramBotAdapter, kandinskyAdapter, telegramBotConfig)
	app := NewApp(configurator, appConfig, loggerConfig, errorsHandler, healthRouter, metricsRouter, telegramRouter, telegramBotAdapter, service, cronusService)
	return app, nil
}

// server.go:

// ServerSet
var ServerSet = wire.NewSet(Set)
